name: XSLT Transform

on:
  push:
    branches:
      - main
    paths:
      - statnice.xml
permissions:
  contents: write

jobs:
  xslt-transform:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          java-package: 'jre'

      - name: Download xmlresolver
        run: |
          curl -L -o xmlresolver.jar https://repo1.maven.org/maven2/org/xmlresolver/xmlresolver/6.0.18/xmlresolver-6.0.18.jar
        
      - name: Download Saxon HE 12.7
        run: |
          curl -L -o saxon-he.jar https://repo1.maven.org/maven2/net/sf/saxon/Saxon-HE/12.7/Saxon-HE-12.7.jar
          
      - name: Use Saxon HE to transform XML to FO
        run: |
          java -cp "saxon-he.jar:xmlresolver.jar" net.sf.saxon.Transform -s:statnice.xml -xsl:statnice.xslt -o:statnice.fo

      - name: Use Saxon HE to transform XML to HTML
        run: |
          java -cp "saxon-he.jar:xmlresolver.jar" net.sf.saxon.Transform -s:statnice.xml -xsl:statnice-html.xslt -o:page/statnice.html

      - name: Download Apache FOP
        run: |
          curl -L -o fop-bin.tar.gz https://downloads.apache.org/xmlgraphics/fop/binaries/fop-2.11-bin.tar.gz
          tar -xzf fop-bin.tar.gz
          mv fop-2.11 fop

      - name: Convert FO to PDF with FOP
        run: |
          ./fop/fop/fop -c fop.xconf -fo statnice.fo -pdf page/statnice.pdf

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add page/statnice.pdf page/statnice.html
          git commit -m "Automated XSLT transformation"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
